Document: amxa-webmenu-extra
Title: Debian amxa-webmenu-extra Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-webmenu-extra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-webmenu-extra/amxa-webmenu-extra.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-webmenu-extra/amxa-webmenu-extra.ps.gz

Format: text
Files: /usr/share/doc/amxa-webmenu-extra/amxa-webmenu-extra.text.gz

Format: HTML
Index: /usr/share/doc/amxa-webmenu-extra/html/index.html
Files: /usr/share/doc/amxa-webmenu-extra/html/*.html
